database:
  main:
    host: localhost
    port: 5432
    username: postgres
    password: postgres
    dbname: dplk
    adapter: postgres
    logLevel: 3
    slowThreshold: 1 # in second
    schema: public
  redis:
    host: localhost
    port: 6379
    username:
    password: